# Fully corrected cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the container image using the correct 'pack build' syntax
  - name: 'gcr.io/k8s-skaffold/pack'
    id: 'Build'
    # The 'env' section to skip tests can be kept for now to isolate issues.
    # You can remove this 'env' block later to re-enable tests.
    env:
      - 'GOOGLE_RUNTIME_VERSION=17'
      - 'GOOGLE_FUNCTION_TARGET=com.example.MyFunction'
      - 'BP_MAVEN_BUILD_ARGUMENTS=clean package -DskipTests=true'
    args:
      - 'build'
      # ARGUMENT 1: The required <image-name>. This must come first.
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-solutions/${_SERVICE_NAME}:$SHORT_SHA'
      # FLAG 1: The builder to use.
      - '--builder=gcr.io/buildpacks/builder:v1'
      # FLAG 2: The environment variable telling the buildpack your main function class.
      - '--env=GOOGLE_FUNCTION_TARGET=com.example.MyFunction'

  # Step 2: Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-solutions/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'

substitutions:
  _SERVICE_NAME: 'my-function-b-service' # Using all lowercase is best practice
  _REGION: 'us-central1'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-solutions/${_SERVICE_NAME}:$SHORT_SHA'